### ISSUE TITLE
[FEAT] solver plugin

### ISSUE THREAD

**Issue by JarbasAl** [NeonGeckoCom/neon-llm-chatgpt#2]
### Objective

OPM

### Initial Implementation Requirements

provide neon solver plugin in setup.py for integration with persona https://github.com/OpenVoiceOS/ovos-core/issues/297

**Comment by NeonDaniel** [comment]
We should consider if these LLM MQ modules should be implemented as solvers directly, or implement the clients, similar to the remote TTS plugins

**Comment by JarbasAl** [comment]
the plan is to have a solver server dockerfile, like we have for tts/stt, which can then load whatever solver it needs and cover remote needs

**Comment by NeonDaniel** [comment]
So, for this repository the work to be done is to add a class that extends `neon_solvers.AbstractSolver`.

**Comment by JarbasAl** [comment]
> So, for this repository the work to be done is to add a class that extends `neon_solvers.AbstractSolver`.

yes, but the class now comes from OPM like other plugins, neon_solvers is providing the service only
